import { ConnectButton } from "@rainbow-me/rainbowkit";
import type { NextPage } from "next";
import Head from "next/head";
import styles from "../styles/Home.module.css";
import dynamic from "next/dynamic";
import { useSigner } from "wagmi";
import { providers } from "ethers";
const DynamicBridge = dynamic(
  // @ts-ignore
  () => import("@socket.tech/widget").then((mod) => mod.Bridge),
  {
    ssr: false,
  }
);

const Home: NextPage = () => {
  const { data: signer } = useSigner();
  const web3Provider =
    signer?.provider &&
    new providers.Web3Provider((signer?.provider as any).provider);
  return (
    <div className={styles.container}>
      <Head>
        <title>RainbowKit App</title>
        <meta
          name="description"
          content="Generated by @rainbow-me/create-rainbowkit"
        />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <ConnectButton />

        {!(typeof window === "undefined") && web3Provider && (
          <DynamicBridge
            // @ts-ignore
            provider={web3Provider}
            API_KEY="645b2c8c-5825-4930-baf3-d9b997fcd88c"
          />
        )}
      </main>

      <footer className={styles.footer}>
        <a href="https://rainbow.me" target="_blank" rel="noopener noreferrer">
          Made with ❤️ by your frens at 🌈
        </a>
      </footer>
    </div>
  );
};

export default Home;
